# Generated by Django 6.0 on 2025-12-14 12:08

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[main.models.date_of_birth_validate]),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[main.models.date_of_birth_validate]),
        ),
    ]
