# Generated by Django 5.1.2 on 2024-10-30 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff_Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.staff"
                    ),
                ),
            ],
        ),
    ]
