# Generated by Django 5.1.2 on 2024-10-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_staff_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_notification",
            name="status",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
