# Generated by Django 5.1.2 on 2024-10-31 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_staff_notification_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff_leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_date", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("status", models.IntegerField(default=0, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.staff"
                    ),
                ),
            ],
        ),
    ]
