# Generated by Django 5.1.2 on 2024-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_student_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
