# Generated by Django 5.1.2 on 2024-11-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_student_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="created_date",
            field=models.DateTimeField(null=True),
        ),
    ]
