# Generated by Django 5.1.2 on 2024-11-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_subject_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
