# Generated by Django 5.1.3 on 2025-01-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_remove_attendance_report_attendance_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
