# Generated by Django 5.1.3 on 2025-01-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_staff_date_of_birth_student_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="short_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
