# Generated by Django 5.1.3 on 2025-01-28 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_course_course_code_course_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name=datetime.date(2024, 12, 29)),
        ),
        migrations.AlterField(
            model_name="staff_leave",
            name="leave_date",
            field=models.DateTimeField(
                null=True, verbose_name=datetime.date(2025, 1, 27)
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name=datetime.date(2024, 1, 29)),
        ),
        migrations.AlterField(
            model_name="student_leave",
            name="leave_date",
            field=models.DateTimeField(
                null=True, verbose_name=datetime.date(2025, 1, 27)
            ),
        ),
    ]
